### ISSUE TITLE
InstalWizard

### ISSUE THREAD

**Issue by SebT34** [XoopsModules25x/moduleinstaller#8]
Hi, 

I try to install the module, but i obtain an error:
`Error: Error: Class 'XoopsModules/Moduleinstaller/InstallWizard' not found in file /modules/moduleinstaller/include/common.inc.php line 63`
Maybe i miss somthing during the installation?
Did you have an idea about how to solve it?
Thanks by advance. (Again 👍 )

**Comment by mambax7** [comment]
Try the [1.04 RC-1](https://github.com/XoopsModules25x/moduleinstaller/releases/tag/1.04_RC-1)  and see if it works for you. 
Please also use the [latest code from the upcoming XOOPS 2.5.11](https://github.com/XOOPS/XoopsCore25/archive/master.zip)

Let me know if it worked for you...

**Comment by SebT34** [comment]
Thanks for your answer. 

I have tried with total new installation (X2.5.11) and 1.04 RC1 (With the links you give to me). And nothing else...

And i obtain the same error...

Error: Error: Class 'XoopsModules/Moduleinstaller/InstallWizard' not found in file /modules/moduleinstaller/include/common.inc.php line 63

**Comment by mambax7** [comment]
OK, I see what it is. Please rename the file in /class from:

installwizard.php

to

InstallWizard.php

Thank you for letting me know and for your testing!

**Comment by mambax7** [comment]
Thank you again for the testing and for reporting it. 
It should be fixed now in https://github.com/XoopsModules25x/moduleinstaller/releases/tag/1.04_RC-2
